from minos.common import MinosException


class MinosNetworkException(MinosException):
    pass
