from minos.common.exceptions import MinosException


class MinosSagaException(MinosException):
    pass
